### ISSUE TITLE
just installed it; it does not find the config file

### ISSUE THREAD

**Issue by vpatryshev** [scalastyle/scalastyle#172]
Here's what I get. I wonder what I do wrong...

```
[info] Loading project definition from /Users/vpatryshev/projects/hex/Backend2/project
[info] Set current project to Backend2 (in build file:/Users/vpatryshev/projects/hex/Backend2/)
[info] scalastyle using config /Users/vpatryshev/projects/hex/Backend2/scalastyle-config.xml
java.lang.RuntimeException: config does not exist: scalastyle-config.xml
    at scala.sys.package$.error(package.scala:27)
    at org.scalastyle.sbt.Tasks$.doScalastyle(Plugin.scala:177)
    at org.scalastyle.sbt.ScalastylePlugin$$anonfun$rawScalastyleSettings$1$$anonfun$apply$1$$anonfun$apply$2.apply(Plugin.scala:88)
    at org.scalastyle.sbt.ScalastylePlugin$$anonfun$rawScalastyleSettings$1$$anonfun$apply$1$$anonfun$apply$2.apply(Plugin.scala:76)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
```

**Comment by vpatryshev** [comment]
Also, I can just fork it and fix, ok?

**Comment by matthewfarwell** [comment]
There is no default config file - you have to create it. There is a task for this - generateConfig. This will give you a base with which you can work.

**Comment by matthewfarwell** [comment]
Closing, presumed fixed.
